version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka0:
    image: wurstmeister/kafka
    container_name: kafka0
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 110
      KAFKA_LISTENERS: 'PLAINTEXT://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka0:9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'

    depends_on:
      - zookeeper


  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 111
      KAFKA_LISTENERS: 'PLAINTEXT://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9093'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'

    depends_on:
      - zookeeper